id: P000642
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AT874
  title: སློབ་དཔོན་ཀླུ་སྒྲུབ་དང་རྒྱལ་བུ་བདེ་བྱེད་བཟང་པོས་མཛད་པའི་རོ་དངོས་གྲུབ་ཅན་གྱི་སྒྲུང་ངོ་མཚར་རྨད་བྱུང་
  author: ''
  volumes:
    a86b859e90d249a1bb67c9518422082a:
      image_group_id: I1KG2225
      title: ''
      volume_number: 1
      total_pages: 65
