id: P000642
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-16 15:55:33.756546
source_metadata:
  id: bdr:W1AT874
  title: སློབ་དཔོན་ཀླུ་སྒྲུབ་དང་རྒྱལ་བུ་བདེ་བྱེད་བཟང་པོས་མཛད་པའི་རོ་དངོས་གྲུབ་ཅན་གྱི་སྒྲུང་ངོ་མཚར་རྨད་བྱུང་
  author: ''
  volumes:
    a86b859e90d249a1bb67c9518422082a:
      image_group_id: I1KG2225
      title: ''
      volume_number: 1
      total_pages: 65
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
