id: opecha:P000642
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AT874
  title: སློབ་དཔོན་ཀླུ་སྒྲུབ་དང་རྒྱལ་བུ་བདེ་བྱེད་བཟང་པོས་མཛད་པའི་རོ་དངོས་གྲུབ་ཅན་གྱི་སྒྲུང་ངོ་མཚར་རྨད་བྱུང་
  volume: ''
  author: ''
