id: I9767CCFF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T15:58:01+00:00'
last_modified: '2022-06-07T12:32:24.567686+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AT874
  title: སློབ་དཔོན་ཀླུ་སྒྲུབ་དང་རྒྱལ་བུ་བདེ་བྱེད་བཟང་པོས་མཛད་པའི་རོ་དངོས་གྲུབ་ཅན་གྱི་སྒྲུང་ངོ་མཚར་རྨད་བྱུང་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    42CC:
      image_group_id: I1KG2225
      title: ''
      total_pages: 65
      order: 1
      base_file: 42CC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
